# Generated by Django 5.1.1 on 2024-10-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_comments_post_alter_comments_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
