# Generated by Django 5.1.1 on 2024-10-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
